### ISSUE TITLE
Custom FOV by default

### ISSUE THREAD

**Issue by plzdonttrack** [Drahsid/FFXIITZA-FPS-Unlocker#10]
When the .ini is created, by default the FOV is set to 83.
At least in my case, this is undesirable, and I haven't the foggiest idea what the game's normal FOV value is, and setting the value without a number freezes the game.

In other words, I suggest the default setting of the FOV variable be the same as the regular, unmodified game. Or at least informing the user of the regular FOV value in a comment.

Eg. #The in-game field of view. [Default: XX, Recommended: User Preference]

**Comment by Drahsid** [comment]
Thanks for the input. The default FOV is 45, I will change this in the next release.
