### ISSUE TITLE
Game locks up when changing zones.

### ISSUE THREAD

**Issue by because-bot-fed** [Drahsid/FFXIITZA-FPS-Unlocker#23]
GTX970, Windows7, borderless windowed.

I gutted the .ini of everything except FoV because that's all I care about, but I can't change zones without it freezing the game. The game is still running and using CPU but totally unresponsive and won't respond to normal "exit" commands, has to be killed in task manager. (Thought it does pop up the "do you want to exit" confirmation, it just doesn't actually close when you click OK)

**Comment by Drahsid** [comment]
Hey thanks for the issue report!
Firstly, when the game crashes, if it is using your storage, naviagate to the game directory (where the exe is) and delete any files that end in .dmp.
Secondly, if your settings file only has the FOV option, then you goofed up. Every option ought to be in the file, or it will use the in-program defaults (which might cause an issue, I haven't tested gutting the file.) If you remove the "Version" setting, then it will automatically add the other options to the file again.
Can you post your settings file? Thanks.

**Comment by because-bot-fed** [comment]
I've reset everything to default, so all config file stuff is default.

I tried with just FoV @ 60, and with it at the default 45.

Even vanilla config the game freezes when it changes zone. 

If I try to run it at the title screen it freezes instantly. 

If I run it while in-game, don't change zones (no freeze yet) and close the tool, zoning will still freeze the game.


My config is default, however if you want to verify for yourself, below is a copy. 


`# File version. Changing this will cause the config to update.
Version=3

# In game frametime target. [Default: 60, Recommended: A limit that your PC can hit]
Framerate=60.000000

# In game frametime target while in menus. [Default: 60, Recommended: A limit that your PC can hit]
Framerate_Menus=60.000000

# In game frametime target while viewing the in game movies/fmvs. [Default: 59.97, Recommended: Default]
Framerate_Movies=59.978000

# In game frametime target while the game window is not in focus. [Default: 60, Recommended: A lower value if the game is hogging resources]
Framerate_NoFocus=30.000000

# The number of times the main loop will run per frame. A higher number results in slightly more accurate predictions, but also slightly increases cpu usage. [Recommended: 2]
Main_Thread_Update_Coef=3.000000

# The in-game Field of View. If you feel claustrophic, or that the viewing angle is too small, consider raising this. [Default: 45, Recommended: User Preference]
Field_of_View=45.000000

# The in-game gamma (brightness). [Default: 45, Recommended: User Preference]
Gamma=45.000000

# The 1x speed state of the in-game-multiplier. [Default: 1, Recommended: 1]
IGM_State0_Override=1.000000

# The 2x speed state of the in-game-multiplier. [Default: 2, Recommended: User Preference]
IGM_State1_Override=2.000000

# The 4x speed state of the in-game-multiplier. [Default: 4, Recommended: User Preference]
IGM_State2_Override=4.000000

# The mouse speed multiplier. This works in conjunction with Enable_Locked_Mouse_Multi and Enable_Adaptive_Mouse. At least one of them must be enabled for this to be used. [Default: 2, Recommended: User Preference]
Locked_Mouse_Multi=2.000000

# Disable the framerate limit completely by erasing related opcodes. [Default: Off, Recommended: Off]
Enable_Full_Speed_Mode=0

# Enabling this will make the mouse speed scale relativley to your framerate AND to the in game multiplier. This fixes mouse speed issues found in the vanilla game. [Default: On, Recommended: On]
Enable_Adaptive_Mouse=1

# Enabling this will stop the game from taking control over the mouse speed multiplier. This is ignored if Enable_Adaptive_Mouse is on. [Default: On, Recommended: On]
Enable_Locked_Mouse_Multi=1

# Enabling this will cause certain variables to ease when they are changed, such as the IGM. [Default: On, Recommended: User Preference]
Enable_Easing=1

# This value can be set to Linear, OnePointFive, Square, Cubic, Quad, Quint, Sine, SinSq, SinInvSq, PerlinFast, or Perlin. This changes the default equation used to smooth out igm changes, where linear is flat, and quint is the sharpest. [Default: SinSq, Recommended: User Preference]
# You can find a visualization of the different easing types here: desmos.com/calculator/l1jiznfdof 
EasingType=SinSq

# The time taken to ease into the next igm state. [Default: 0.5, Recommended: User Preference]
EasingTime=0.500000

`

**Comment by Drahsid** [comment]
Is the console outputting anything? Furthermore, do you have any other mod patches installed?

**Comment by Drahsid** [comment]
Could you tell me what CPU and version of the program you are running?
Furthermore, could you send me the [MD5](http://onlinemd5.com) sum of your FFXII_TZA exe?

**Comment by because-bot-fed** [comment]
If you mean version of your tool, it's the one from Nexus, not sure what version offhand, it was the only file available. 

I just downloaded the github relaese from 2 days ago, but same problem.

https://i.imgur.com/nurwAJ3.png

Nothing new in the console with this version of the tool. 

CPU is i5 4690K
FF12 file version is just 1.0 according to the properties
MD5 is D032914AC59BAFDD62F038832CC14525

**Comment by because-bot-fed** [comment]
Nope, unfortunately (or fortunately) this is my first time trying to use your mod, I have no connection to that other person. 

I'm more than happy to help troubleshoot if it adds any value for you, but if it doesn't make any difference for you either way, ultimately the only thing that really matters to me is getting the FOV zoomed out a bit... If there's a chance you could toss something together that only has that, I don't think the FOV functionality is playing a part in if it freezes or not. Up to you if that's something you're interested/willing to do, either way just let me know. :)

**Comment by Drahsid** [comment]
I do not intend to make a separate mod for only FOV. The source code is however available under a MIT license and you are free to take the part of the code that does this and make it yourself. 
I am currently examining the differences between the different versions of the game which I have, give me a few minutes and I may know what's going on.

**Comment by Drahsid** [comment]
Hey, I found the problem.
I know we all don't like spending money on games; the MD5 of your files matches up with CPY's crack. I do not intend to fix issues related to patches (such as this one, which is a workaround to Denuvo). In the future, I will update the program to inform users who have patched their game that it may be less functional. Furthermore, I will specifically check for this MD5 and simply inform the user that this version of the file does not work with my program. If you want the full feature-set of my program, then you must use a proper installation of the game. Otherwise, you can of course build the source yourself with only the features you want.

**Comment by because-bot-fed** [comment]
https://i.imgur.com/2NXNaGp.png

I own the game, but I also generally speaking refuse to run games with garbage DRM on them when avoidable, or have to have steam running at all times just to play something I own. You do you dude, but yes, please update your nexus entry and github frontpage to at least not be wasting people's time if this is your stance.

**Comment by Drahsid** [comment]
Not sure if you misinterpreted my stance, or I misinterpreted how you feel; I don't really care that you're running CPY's version of the game, it simply introduces bugs that I do not intend to fix. As I said before, the program is open source so if there's a particular part that is wanted from it, it ought be easy to implement. 
Honestly though I'm not sure why you would say "No other mods..." then send you the MD5 of your Denuvo-modded exe. A lot more time would have been saved if you were open about this.
