### ISSUE TITLE
Error message 0x10202623 

### ISSUE THREAD

**Issue by bryanbuty** [Drahsid/FFXIITZA-FPS-Unlocker#26]
Can't seem to make it work, always gives the error in any exe version.

**Comment by Drahsid** [comment]
Are you getting this error inside of the exe's console, or is it a windows' error message?

**Comment by bryanbuty** [comment]
It's on the cmd, I also got other errors but they all seem to prevent the unlocker to work. I tried the other exes and some of them I could change FPS/FOV, but as soon as I tried to cross any blue line in game it crashed.

**Comment by Drahsid** [comment]
Can you send a screenshot of the latest version of the program after it has posted the error message?

**Comment by bryanbuty** [comment]
There you go [https://imgur.com/a/VSKGLtU](url)

**Comment by Drahsid** [comment]
The MD5 D032914AC59BAFDD62F038832CC14525 is from the CPY-cracked version of the game. That is a fake error message that I made for fun. I do not intend to fix issues related to non-legitimate versions of the game.

**Comment by bryanbuty** [comment]
Changing things from legit games are piracy too. But that's alright.

**Comment by Drahsid** [comment]
Guess all of those Skyrim modders are pirates ¯\_(ツ)_/¯
If I removed the fake error message the program would just crash the game. This only happens on the CPY-cracked version of the game so I do not intend to fix it.

**Comment by bryanbuty** [comment]
The mod It's yours, you don't need to and yes, if you modify a game that is not yours, it's piracy.
