### ISSUE TITLE
Monitor refresh rate

### ISSUE THREAD

**Issue by MrPick1es** [Drahsid/FFXIITZA-FPS-Unlocker#27]
Every time I start the game in fullscreen non-borderless the game changes my refresh rate to 60. Any idea how to fix this? I would prefer to play in true fullscreen, thanks!

**Comment by Drahsid** [comment]
Hey thanks for posting the issue. Please make sure that Vsync is disabled both in game and in your driver settings. I do however suggest using borderless mode, full screen mode has audio syncing issues without the mod (when you drop frames) so I imagine it is worse with the mod.

**Comment by MrPick1es** [comment]
Ok thanks for the reply. I'm now giving it a try at 144hz and it seems crazy fast at "1x" speed.

**Comment by Drahsid** [comment]
If you launched the program after loading into the game, simply change scenes (go to a different area) and the speed should become normal.

**Comment by MrPick1es** [comment]
Thanks for the help, not sure which variable I had wrong at which point but it seems all is good now! I was just about to jump back into the game after not playing for months when I check PCgamingwiki and saw your mod, thanks again! Game should be much more fun like this.

**Comment by Drahsid** [comment]
Whoa- wasn't aware it ended up on there!
I suggest setting your menu and movie fps options to 60 so that you don't get completely desynced during cutscenes. I have yet to resolve said issue. Other than that it should work great.
If you have any more issues, you can post them here. Otherwise, you can add me on Discord (Drahsid#5152) and I will be glad to answer and questions.

**Comment by MrPick1es** [comment]
It says you can't be added on discord as per a setting you set.

Game doesn't seem to run properly in trial mode, which I'm messing around with, in the second scene it speeds up.

**Comment by Drahsid** [comment]
Sorry had the everyone option off. Try adding me again. I haven't done any testing in trail mode; that issue might be related to #20
