### ISSUE TITLE
Update 1.0.3.0 has changed the memory addresses

### ISSUE THREAD

**Issue by Drahsid** [Drahsid/FFXIITZA-FPS-Unlocker#28]
The program now crashes the game when ran. I am currently working on the solution.

**Comment by ajhix36** [comment]
Are you still working on this? I really need my ffxii fix and I'd love to play over 60 fps. <3

**Comment by Drahsid** [comment]
@ajhix36 Yes, I've been working on it slowly; at some point an updated revision will be released.

**Comment by ajhix36** [comment]
Ty ty ty <3
